<?php

namespace src\models\AirportClasses\Ticket\classes\Ticket;

/**
 * Ticket
 * 
 * Mainly is used in `Flight` object.
 * 
 * It should be generated by `TicketManagerTrait` function 
 * `generateTickets()`.
 */
class Ticket {
  /**
   * @var string $id ID of this ticket.
   * Contains `Flight` ID and seat id. 
   */
  protected string $id;

  /**
   * @var string
   */
  protected string $flightId;

  /**
   * @var int $rowNo Row number of `Plane` `$seats` for
   * this ticket.
   */
  protected int $rowNo;

  /**
   * @var string $seatId Seat ID for this `Ticket`, Contains One
   * letter and one number.
   */
  protected string $seatId;

  /**
   * @var string $price Price of this `Ticket`.
   */
  protected string $price;

  public function __construct(
    string $id,
    string $flightId,
    int $rowNo,
    string $seatId,
    string $price,
  ) {
    $this->id = $id;
    $this->flightId = $flightId;
    $this->$rowNo = $rowNo;
    $this->seatId = $seatId;
    $this->price = $price;

    // print('New ticket #' . $this->id . ' (row "' 
    // . $rowNo . '"), price: ' . $price . PHP_EOL);
  }
}